### ISSUE TITLE
an unwanted character is added after bold

### ISSUE THREAD

**Issue by herverenault** [theZiz/aha#21]
Compiled from ea38baae20d5e7019d7e6eb2fcb480523eb65589
```
$ echo $( tput bold )"foo"$( tput sgr0 )"bar" | ~/aha/aha 
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!-- This file was created with the aha Ansi HTML Adapter. https://github.com/theZiz/aha -->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="application/xml+xhtml; charset=UTF-8" />
<title>stdin</title>
</head>
<body>
<pre>
<span style="font-weight:bold;">fooB</span>bar
</pre>
</body>
</html>
```
(There's a **B** after foo)

**Comment by herverenault** [comment]
Happens on Ubuntu 16.04 too.

**Comment by theZiz** [comment]
Fixed here: https://github.com/theZiz/aha/commit/721c8f4e525a3e040ec9f999ee0aeb96e93ddacc
In fact the bug was in tput as ```tput sgr0``` does not only reset the terminal, but also resets the ASCII character set back to the US character set with "ESC ( B ESC [ m". In the past I just read ESC * parameters, where * could be anything. Now I explicitly check for [, which broke "support" for tput sgr0. In fact it was just luck, that it worked beforehand. Now I added an explicit check for ESC ( * to ignore it. ;)
