### ISSUE TITLE
Overlapping highlight and foreground colour

### ISSUE THREAD

**Issue by anoother** [theZiz/aha#36]
When given a character whose highlight and text colour match, the terminal will render text using its background colour (essentially 'punching through' the highlight).

`aha`, however, renders the text in its own highlight colour -- resulting in a solid block in the HTML output, whose text can only be read by block-selecting it.

When text and highlight colour match, `aha` should therefore render text in the chosen/specified terminal background colour, as opposed to the ANSI colour currently in use.

**Comment by theZiz** [comment]
First of all, sorry for the **big** delay. For some reasons from time to time I totally overlook issues. >.<

Secondly, I know that this can happen if you e.g. use the white background sheme and then change the foreground colours (which is why I like the black background scheme the most). But in which use cases is a text with the same, explicit set (!) background and foreground colour, seeable in the terminal but not in `aha`? I would guess that the terminal would render a solid block, too.

**Comment by anoother** [comment]
I can't actually remember how/why I wanted this, or what the specific circumstance was :grin: 

I'll see if I can dig it back out.

**Comment by briantully** [comment]
not sure if this is related, but I am frequently getting results where text color and background color are getting set the same, making the text output unreadable. I typically like to use `aha --black` and wind up getting lines of text with white text color and white background. I typically have to edit the resulting HTML file to modify all occurrences of `<span style="color:black;background-color:black;">` and `<span style="color:white;background-color:white;">`so that the text color and background-color are not the same.

**Comment by theZiz** [comment]
@briantully Could you give me a command or a textfile with  ANSI color steering codes still inside, so I can reproduce the issue?
